import type { Metadata } from "next";
import { ArrowRight, Check, ClipboardCheck, Eye, Handshake, MessagesSquare, Route, ShieldCheck } from "lucide-react";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "About Us | Yorkshire Fortress Security", description: "A Yorkshire-rooted security company built around professional people, clear standards and dependable service." };

export default function AboutPage() { return <main><SiteHeader /><PageHero eyebrow="About Yorkshire Fortress" title="Strong values. Capable people. Safer places." copy="A Yorkshire-rooted security partner committed to professional standards and dependable protection." image="/media/security-guard.jpg" />
  <section className="yfs-section yfs-about-story" id="main"><div><p className="yfs-kicker">About our company</p><h2>Professional security, shaped around the people and places it protects.</h2></div><div><p className="lead">Yorkshire Fortress Security is a Yorkshire-rooted security company providing guarding, key holding, alarm response, door supervision, vehicle patrol inspections and event security.</p><p>We support organisations that want more than a uniform at the door. Our role is to understand how a site operates, identify where security can reduce risk and build a service with clear responsibilities, communication and evidence of delivery.</p><p>That may mean a dedicated guarding presence during operating hours, controlled access outside them, mobile checks across several properties or a planned team for a busy event. Services can stand alone or work together under one coordinated approach.</p><p>We bring Yorkshire directness, care and practical judgement to every assignment. Clients should know who is protecting them, what that person is expected to do, how incidents will be escalated and how performance will be reviewed.</p></div></section>
  <section className="yfs-values-grid"><div><ShieldCheck /><span>01</span><h3>Professional</h3><p>Well-presented, well-briefed people who understand the responsibility placed in them.</p></div><div><Eye /><span>02</span><h3>Vigilant</h3><p>Active observation, useful reporting and early action when something is not right.</p></div><div><Handshake /><span>03</span><h3>Dependable</h3><p>Clear communication and consistent delivery—during routine shifts and unexpected incidents.</p></div></section>
  <section className="yfs-team-standard"><div><img src="/media/door-supervisors.jpg" alt="Security professional managing a busy public event" /></div><div><p className="yfs-kicker tan">Our people</p><h2>The standard starts with who we put on your site.</h2><p>We look for calm judgement, communication and pride in the job. Site-specific briefings and active supervision help officers understand not only what to do, but why it matters.</p><ul><li><Check /> Role and site-appropriate selection</li><li><Check /> Clear responsibilities and escalation routes</li><li><Check /> Ongoing performance support</li></ul><a href="/services">Explore our services <ArrowRight /></a></div></section>
  <section className="yfs-section yfs-company-model"><div className="yfs-title-row"><div><p className="yfs-kicker">Our service model</p><h2>Clear from first review to everyday delivery.</h2></div></div><div className="yfs-company-model-grid"><article><Route /><span>01</span><h3>Understand the environment</h3><p>We consider the site, operating hours, access patterns, people, assets, known incidents and the outcome the client needs.</p></article><article><ClipboardCheck /><span>02</span><h3>Define the assignment</h3><p>Roles, patrols, checkpoints, escalation contacts and reporting expectations are written clearly before the service begins.</p></article><article><MessagesSquare /><span>03</span><h3>Keep communication open</h3><p>Useful reporting and a clear management route keep clients informed during routine delivery and when circumstances change.</p></article><article><Eye /><span>04</span><h3>Review and improve</h3><p>Performance, incidents and operational changes inform adjustments to the security plan so the service stays relevant.</p></article></div></section>
  <section className="yfs-assurance"><div><ShieldCheck /><h2>Need a security plan built around your site?</h2><p>Tell us what you protect, when you operate and where the pressure points are. We can help shape a proportionate service.</p></div><a href="/contact">Talk to our team <ArrowRight /></a></section>
  <SiteFooter /></main>; }
