import type { Metadata } from "next";
import { ArrowRight, Mail } from "lucide-react";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { insights } from "../data";
import { kicker, kickerTan, primaryButton, section, sectionHeading } from "../styles";

export const metadata: Metadata = { title: "Insights & News | Yorkshire Fortress Security", description: "Practical security guidance for safer people, places and operations." };

export default function InsightsPage() { return <main><SiteHeader /><PageHero eyebrow="Insights & news" title="Practical guidance for safer places." copy="Clear thinking on guarding, response, patrols, events and the risks security leaders face every day." image="/media/alarm-response.jpg" />
  <section className={section} id="main"><div className="mb-12"><p className={kicker}>Latest thinking</p><h2 className={`${sectionHeading} max-w-[800px]`}>Useful, considered and ready to apply.</h2></div><div className="grid grid-cols-3 gap-6 max-lg:grid-cols-2 max-sm:grid-cols-1">{insights.map((item) => <article className="border-b-4 border-navy bg-paper" key={item.title}><a className="relative block h-[280px] overflow-hidden" href="#contact"><img className="h-full w-full object-cover transition duration-500 hover:scale-105" src={item.image} alt="" /><span className="absolute bottom-0 left-0 bg-tan px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.12em]">{item.category}</span></a><div className="p-6"><small className="text-[11px] uppercase tracking-[.1em] text-muted">{item.date}</small><h3 className="my-3 text-[23px] leading-[1.15] text-navy">{item.title}</h3><p className="text-sm text-muted">{item.copy}</p><a className="flex items-center gap-2 text-sm font-extrabold text-navy" href="#contact">Read insight <ArrowRight size={17} /></a></div></article>)}</div></section>
  <section className="flex items-center gap-7 bg-navy px-[max(24px,calc((100vw_-_1240px)/2))] py-[75px] text-white max-lg:flex-wrap max-sm:px-[18px]"><Mail className="shrink-0 text-tan" size={48} /><div className="mr-auto"><p className={kickerTan}>Stay informed</p><h2 className="m-0 text-[clamp(32px,4vw,48px)] leading-[1.05]">Security insight, without the noise.</h2><p className="mb-0 text-[#cdd5df]">Occasional practical guidance for people responsible for sites, teams and operations.</p></div><a className={`${primaryButton} shrink-0`} href="mailto:info@yorkshirefortresssecurity.co.uk">Join the update list <ArrowRight /></a></section><SiteFooter /></main>; }
